apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: yogeshsolunke/demo:latest   # Jenkins will replace with :$BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet: { path: /actuator/health, port: 9090 }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 9090 }
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
spec:
  selector:
    app: demo
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      nodePort: 30090
